server.port: 9090
 
spring.profiles.active: local

# db connection info
spring:
  datasource:
    #initialization-mode=never
    # log4jdbc
    ## PostgreSQL ----------------------------------
    # 'org.postgresql:postgresql:42.2.20'    
    #driverClassName: org.postgresql.Driver
    #url: jdbc:postgresql://localhost:5432/tenq
    ## Mysql ----------------------------------
    # 'mysql:mysql-connector-java:5.1.49' 
    # driverClassName: com.mysql.cj.jdbc.Driver
    # url: jdbc:mysql://localhost:3306/tenq?autoReconnect=true&useUnicode=true&characterEncoding=UTF8&verifyServerCertificate=false&useSSL=false&&serverTimezone=UTC
    ## Oracle ----------------------------------
    # 'com.oracle.jdbc:ojdbc8:12.2.0.1' 
    # driverClassName: oracle.jdbc.driver.OracleDriver
    # url: jdbc:oracle:thin:@localhost:1521/xe    
    ##  log4jdbc  Driver-----------------------------------------------------
    driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    ## PostgreSQL ----------------------------------
    #url: jdbc:log4jdbc:postgresql://localhost:5432/tenq
    ## mysql ----------------------------------
    #url: jdbc:log4jdbc:mysql://localhost:3306/tenq?autoReconnect=true&useUnicode=true&characterEncoding=UTF8
    ## mariadb ----------------------------------
    #url: jdbc:log4jdbc:mariadb://localhost:3306/testdb
    ## Oracle ----------------------------------
    #url: jdbc:log4jdbc:oracle:thin:@localhost:1521/xe
    url: jdbc:log4jdbc:oracle:thin:@172.16.1.183:1521:TPEARL
    ## mysql 
    #username: tenq
    #password: tenq@#
    ## Oracle 
    username: pearl
    password: brnet2000!#%  
    #tomcat:
      #test-on-borrow: true
      #validation-interval: 3000 
      #validation-query: SELECT 1
      
  # HTTP encoding (HttpEncodingProperties)
  http:
    encoding:
      charset: UTF-8
      enabled: true   # Enable http encoding support.
      force: true  # Force the encoding to the configured charset on HTTP requests and responses.
      #log-request-details: true   # 로그에 마스킹 해제  logging.lev
      
  messages:
    basename: message ##  message prefix  file name
    encoding: UTF-8


mybatis:
  mapper-locations: classpath:mappers/**/*.xml
  type-aliases-package: commerce.com.**.domain
  configuration:
    call-setters-on-nulls: true
    mapUnderscoreToCamelCase: true
    lazyLoadingEnabled: true
    aggressiveLazyLoading: false
    jdbc-type-for-null: null
    #default-fetch-size: 100
    #default-statement-timeout: 30


logging:
  config:
    classpath: logback-spring.xml
  #level:
    #web : debug
