server.port: 9090
 
spring.profiles.active: local

# db connection info
spring:
  datasource:
    #initialization-mode=never
    # driver-class-name: com.mysql.cj.jdbc.Driver
    # driverClassName: com.mysql.cj.jdbc.Driver
    driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    # url: jdbc:mysql://localhost:3306/tenq?autoReconnect=true&useUnicode=true&characterEncoding=UTF8&verifyServerCertificate=false&useSSL=false&&serverTimezone=UTC
    url: jdbc:log4jdbc:mysql://localhost:3306/tenq?autoReconnect=true&useUnicode=true&characterEncoding=UTF8
    username: tenq
    password: tenq@#
    #tomcat:
      #test-on-borrow: true
      #validation-interval: 3000 
      #validation-query: SELECT 1
      
  # HTTP encoding (HttpEncodingProperties)
  http:
    encoding:
      charset: UTF-8
      enabled: true   # Enable http encoding support.
      force: true  # Force the encoding to the configured charset on HTTP requests and responses.
      #log-request-details: true   # 로그에 마스킹 해제  logging.lev
      
  messages:
    basename: message ##  message prefix  file name
    encoding: UTF-8


mybatis:
  mapper-locations: classpath:mappers/**/*.xml
  type-aliases-package: commerce.com.**.domain
  configuration:
    call-setters-on-nulls: true
    mapUnderscoreToCamelCase: true
    lazyLoadingEnabled: true
    aggressiveLazyLoading: false
    jdbc-type-for-null: null
    #default-fetch-size: 100
    #default-statement-timeout: 30


logging:
  config:
    classpath: logback-spring.xml
  #level:
    #web : debug
